export const contents = {
    Fourier:{
        sentences:[
            'Every signal in this world can be expressed as the superposition of two or more waves.',
            'This is called the wave superposition principle, which means that any complex signal can be decomposed into several simple signals.',
            'Fourier transform is a fundamental transformation formula that can decompose the input signal into simple sine waves, and all the acoustic signal processing methods used in this app somehow applies this formula.',
            "Let's see the easiest example - if the input signal is the 440 Hz sine wave signal, the result of the Fourier transform shows the sharp peaks at 440 Hz and no power at the other frequencies. Like this, the result of the Fourier transform shows the power of the signal at a certain frequency.",
            'Then how can the Fourier transform be calculated?',
            'The following formula is the definition of the Fourier transform.',
            'The output of Fourier transform may include an imaginary number; therefore, it is necessary to post-process the output so as to make the oupput understandable.',
            'There are two ways to plot the strength of the output, amplitude spectrum and power spectrum.',
            'Amplitude spectrum |F(ω)| is the absolute value of the output, and power spectrum |F(ω)|<sup>2</sup> is the square of the amplitude spectrum.',
            "Now, let's calculate this formula with the input signal mentioned in the last section.",
            'Open the following tab to see the calculation process.',
            'The input signal can be described as follows:',
            'Substituting f(t) to the definition of the Fourier transform gets the following result.',
            'Fig. 2 is a power spectrum, which is the square of the absolute value of F(ω).',
            'Therefore, the power spectrum can be calculated as follows:',
            'Finally, Fig. 2 in the "What is Fourier transform?" section is the plot of the equation above when T is 1 seconds. Fig.1 below is the actual graph of the calculated power spectrum. The negative frequency means the conjugate of the positive frequency of the exponential function.',
            "Then let's move on to more complicated signal.",
            "This time, you don't have to calculate as the process is complicated.",
            'Have you heard the square wave?',
            'It is often used as one of the timbres of the synthesiser, and the audio player below is the 440 Hz of the square wave.',
            'The square wave can be defined as the following formula, and Fig.2 shows its graph.',
            'As you can see from the formula and the gif, the square wave is composed of the fundamental wave and the components of its odd multiples.',
            'Moreover, the amplitude of each wave decreases as the number of harmonics increases (1 → 1/3 → 1/5 → 1/7 →...).',
            "Let's check if we can get the same result from the Fourier transform.",
            'Although the definition of <i>g(t)</i> is complicatied, we can write the square wave in the different ways as follows:',
            "where <i>f0</i> is the fundamental frequency. Let's type this function in any programming language.",
            'This time, I used MATLAB.',
            'As you can see from the result, the ratio of the amplitude is the same as mentioned above.',
            'Have you got the same results as written in the tabs?',
            "However, the Fourier transform's formula above is not what happens on the computer.",
            'The signal input in the computer is somewhat sampled as the computer cannot handle the continuous signal.',
            'Therefore, the Fourier transform should also correspond with it. The discrete version of the Fourier transform is called Discrete Fourier transform (DFT), given by the following formula.',
            'where <i>N</i> is the number of the sampling times.',
            'In practice, Fast Fourier transform (FFT), an algorithm for fast and efficient computation of the DFT, is executed in this app.',
            "So, how is the FFT applied in this app? Let's move on to the spectrogram!"
        ],
        formulas:[
            '$$ { F(\\omega) = \\int_{-\\infty}^{+\\infty}f(t)e^{-j\\omega t}dt}  $$ ',
            '$$ { f(t) =  \\begin{cases}\\sin{\\omega_{1}t} & (-T \\le t \\le +T )\\\\ 0 & \\mathrm{else}\\end{cases} } $$',
            '$$ { \\omega_{1} = 2\\pi\\cdot 440t} $$',
            '$$ { \\begin{eqnarray} F(\\omega) &=& \\int_{-T}^{+T}\\sin{\\omega_{1}t} \\cdot e^{-j\\omega t}dt \\\\ &=& \\int_{-T}^{+T}(\\frac{e^{\\ j\\omega_{1}t}-e^{-j\\omega_{1}t}}{2j})\\cdot e^{-j\\omega t}dt  \\\\ &=& \\frac{1}{2j}\\int_{-T}^{+T}(e^{\\ j(\\omega_{1} - \\omega)t}-e^{\\ j(-\\omega_{1}-\\omega)t}) \\ dt  \\\\ &=& jT(\\frac{\\sin(\\omega_{1}+\\omega)}{\\omega_{1}+\\omega} - \\frac{\\sin(\\omega_{1}-\\omega)}{\\omega_{1}-\\omega})  \\end{eqnarray} }  $$ ',
            '$$ { |F(\\omega)|^2 = T^2(\\frac{\\sin(\\omega_{1}+\\omega)}{\\omega_{1}+\\omega} - \\frac{\\sin(\\omega_{1}-\\omega)}{\\omega_{1}-\\omega})^2} $$',
            '$$ { g(t) = \\frac{4}{\\pi}\\sum_{n=1}^\\infty \\frac{\\sin(2\\pi (2n-1)f_0t)}{2n-1} } $$',
            '$$ { g(t) = \\begin{cases} 1 & (\\frac{k}{f_0} < t \\leq \\frac{k+0.5}{f_0}) \\\\ -1 & (\\frac{k+0.5}{f_0} < t \\leq \\frac{k+1}{f_0}) \\end{cases} } $$',


            '$$ { F(k) = \\sum_{n=0}^{N-1}f[n]e^{-j\\frac{2\\pi k}{N} n} \\ \\ (k = 0,1,2,...,N-1)} $$'
        ],
        images: [
            { src: require('@/assets/theory/FFT_raw.jpg'),    caption: 'Raw Signal of A4 and E5' },
            { src: require('@/assets/theory/FFT_Result.jpg'), caption: 'The FFT result of Fig. 1' },
            { src: require('@/assets/theory/spectrum_440.png'), caption: 'The graph of the calculated power spectrum.' },
            { src: require('@/assets/theory/square.gif'),     caption: 'The graph of the square wave (f0 = 1 Hz) increasing the last number of the sigma notation.' },
            { src: require('../../../assets/theory/square_fft_code.png'), caption: 'The code of generating the square wave (f0 = 1 Hz) and calculating the Fourier transform' },
            { src: require('../../../assets/theory/square_fft.jpg'),      caption: 'The amplitude spectrum of the square wave' },
        ],
        audios: [
            { src: require('@/assets/theory/square.wav'),          title: '440 Hz square wave (watch out for the volume!)' },
        ]
    },
    Spectrogram: {
        sentences: [
            'The spectrogram visualises the input audio file so as to read the temporal changes (i.e. pitch and power) simultaneously.',
            'This method is applied in the many fields (e.g., voiceprint identification, detecting animal sounds, music production, and sonar/radar).',
            "Let's look at the easiest example; 440 Hz sine wave.",
            'The image below is the spectrogram of the sine wave which lasts 5 seconds.',
            'You can check the result visually that the wave has a constant value of 440 Hz until the end.',
            'Then, what will happen when the frequency changes depending on the time?',
            'The audio below is called the exponential swept sine wave, whose formula is written as follows:',
            'where <i>ω<small>1</small></i> and <i>ω<small>2</small></i> are the start and end frequencies of the sweep (in radians) and <i>T</i> is the length of the sweep in seconds.',
            'As you can hear, this sound starts from the low frequency (20 Hz) and rapidly goes up until 22 kHz.',
            'So how will the spectrogram be?',
            'The following image is the spectrogram of the swept sine wave.',
            'The spectrogram successfully illustrates the rise of the frequency.',
            'Thus, as you experienced, the spectrogram is a useful tool to visualise and share with others what is vague and difficult to describe as auditory information.',
            'So, how to create the spectrogram?',
            "Before getting into the spectrogram specification, let's remind the Fourier transform.",
            'The Fourier transform is the method to extract the frequency component of the entire section of the input signal.',
            "So then, don't you think the spectrogram can be created by dividing the input signal into small-time sections and executing the Fourier transform to each of them?",
            'Yes, you are right.',
            'This method is Short-Time Fourier transform (STFT), and the spectrogram is a visualisation of the result of STFT.',
            'The formula of the STFT will be described in the next section.',
            'The formula of the STFT is a variant of the DFT formula; the STFT requires dividing the input signal into small-time sections.',
            'However, dividing the signal is not simple; the window function should be applied as the Fourier transform presupposes the input signal to be a periodic function (i.e. the simple division cannot assure continuity).',
            'The window function is a weighting function to avoid generating discontinuities. There are many types of window functions; however, most are the mountain-shaped function with an apex at the middle of the window and two downward slopes.',
            'One of the most popular windows is the Hann window.',
            'The formula of the Hann window is as follows:',
            'It is possible to eliminate the discontinuity by multiplying it with the window function.',
            'Therefore, the formula of the STFT can be expressed by using the amount of movement per frame <i>R</i> and the current time index <i>m</i> as follows:',
            'The amount of movement per frame is the difference between the window length <i>M</i> and the overlap length <i>L</i> given in Fig. 4.',
            'The overlap method is important in extracting the frequency response as much as possible.',
            'If the overlap percentage is zero, both ends of the frame cannot be extracted by the next/previous frame (due to the window function); it causes the frequency information to be missing at those parts.',
            'Therefore, applying the overlap compensates for the missing part of the signal by making duplicated sections.',
            'In conclusion, the process of the STFT can be expressed by the following steps.',
            'The output of the STFT is the collection of a large amount of the DFT.',
            'Therefore, the power of each element can be expressed by the power spectrum |F(ω)|<sup>2</sup>, and the spectrogram is the plot of the power whose x and y axes are time and frequency, respectively. ',
        ],
        formulas: [
            '$$ { s(t) = \\sin{(\\frac{\\omega_{1}T}{\\mathrm{ln}(\\frac{\\omega_{2}}{\\omega_{1}})}(e^{\\frac{t}{T}\\mathrm{ln}(\\frac{\\omega_{2}}{\\omega_{1}})}-1) )} } $$',
            '$$ { w[n] = 0.5 (1-\\cos{\\frac{2\\pi n}{N}}) } $$',
            '$$ { F(m, k) =  \\sum_{n=0}^{N-1}f[n]w[n-mR]e^{-j\\frac{2\\pi k}{N} n} \\ \\ (k = 0,1,2,...,N-1) } $$'
        ],
        images: [
            { src: require('@/assets/theory/spectrogram_440.png'),   caption: 'The spetrogram of the constant 440 Hz sine wave.' },
            { src: require('@/assets/theory/spectrogram_swept_sine.png'),   caption: 'The spetrogram of the swept sine wave.' },
            { src: require('@/assets/theory/spectrogramsource.png'), caption: 'The source sound of operatic voice' },
            { src: require('@/assets/theory/spectrogram.png'),       caption: 'The spectrogram of Fig.1' },
            { src: require('@/assets/theory/no_window.png'),         caption: 'The simple division without window function. Continuity has disappeared.' },
            { src: require('@/assets/theory/hann_window.jpg'),       caption: 'The graph of Hann window.' },
            { src: require('@/assets/theory/window_usage.png'),       caption: 'Creating the window-filtered signal. By making the bothend to 0, the continuity is guaranteed.' },
            { src: require('@/assets/theory/matlab_stft.png'),       caption: 'The outline of the STFT.' },
        ],
        audios: [
            { src: require('@/assets/theory/swept_sine.wav'),  title: 'The swept sine wave (T = 5, ω1 = 2π*20, ω2 = 2π*22000). (watch out for the volume!)' },
        ]
    },
    IrAnalysis: {
        sentences: [
            'In general, the impulse response is the response of the linear time-invariant system when the impulse signal <i>δ(t)</i>, given in the following equation, is input.',
            'This equation is an ideal signal; instead, the unit impulse signal, shown as follows, is used in practical terms.',
            'So, how does the response against the impulse signal relate to acoustics?',
            'Surprisingly, the acoustic space can be approximated as a linear time-invariant system, and the response of the space against the impulse signal shows the characteristics of the space.',
            "If you don't understand the 'linear' and 'time-invariant', just know that the following equations can be applicable to the acoustic analysis (they are a bit complicated concepts).",
            'In acoustics, the impulse signal is an instantaneous burst.',
            "Imagine the hand clap and gunshots - they are a kind of impulse signal, although they are not 'pure' impulse responses.",
            "But what does this 'pure' mean?",
            "First, let's look at their Fourier spectrums.",
            'As you can see, the spectrums of the hand clap and guns are not constant, whereas that of the unit signal is constant.',
            'The spectrum of the unit impulse signal shows that the signal has equal power across all frequency bands.',
            'Therefore, the impulse response in acoustics is a recording of the direct sound and reverberation of this impulse signal emitted at a point in space, whose formula is written as follows:',
            'In other words, the impulse response equals how much any frequency remains in the reverberation when the impulse signal is input.',
            'Therefore, analysing the impulse response reveals the characteristics of the recorded place.',
            'The Schroeder Curve is the energy decay curve used to quantify the acoustic characteristics of the recorded environment.',
            'This curve was developed by Schroeder[1] which is defined by:',
            'where <i>h(t)</i> is an impulse rseponse. As you can see, the Schroeder Curve is the energy decay curve, which describes the remaining energy at a time point <i>t</i>.',
            'The acoustic characteristics vary with frequency bands; therefore, it is necessary to filter the impulse response with certain frequency bands before calculating the Schroeder curve.',
            'In general, the impulse response is filtered by the octave band band-pass filter, shown in Table 1.',
            'There are five representive acoustic parameters (Reverberation time, Early decay time, C50, C80, and D50) that describes the characteristics of the recorded space.',
            'Expand the following panels to see what each parameter means.'
        ],
        formulas: [
            '$$ { \\delta (t) = \\begin{cases} \\infty & (t = 0) \\\\ 0 & \\mathrm{else} \\end{cases} } $$',
            '$$ { \\delta (t) = \\begin{cases} 1       & (t = 0) \\\\ 0 & \\mathrm{else} \\end{cases} } $$',
            '$$ { h(t) = \\int_{-\\infty}^{+\\infty}h(t-\\tau)\\delta (t)dt } $$',
            '$${ S(t) = {10 \\log_{10}{\\int_t^\\infty h^2(\\tau)d\\tau \\over \\int_0^\\infty h^2(\\tau)d\\tau}} }$$'
        ],
        images: [
            { src: require('@/assets/theory/unitIR_dB.jpg'),    caption: 'The power spectrum of the unit impulse signal.' },
            { src: require('@/assets/theory/hand_clap_ir.png'), caption: 'The power spectrum of the hand clap [1].' },
            { src: require('@/assets/theory/gun_ir.png'),       caption: 'The power spectrum of guns [2].' },
            { src: require('@/assets/theory/IR.png'),           caption: 'The relationship between the impulse signal and impulse response.' },
            { src: require('@/assets/theory/Schroeder.png'),    caption: 'Example of the Schroeder curve.' },
        ]
    },
    Auralisation: {
        sentences: [
            'Auralisation is a method of creating an acoustic virtual reality; it is possible to reproduce a reverberant sound as if the sound source is played in an arbitrary space.',
            "Let's look at an example - the following sound file is an operatic voice recorded in the anechoic chamber.",
            "Now, let's prepare the impulse response. This time, the Usina del Arte concert hall is applied.",
            'Lastly, after the auralisation process, you get the operatic voice virtually sung in the concert hall!',
            'So how to create this kind of auralised sound file? In this app, what you should do is just to follow the steps in the "Auralisation" section.',
            'The formula and its actual process are described in the next section.',
            'Auralisation, in other words, is a process realized by adding a reverberation component (i.e. spatial impulse response) to each sample of the original anechoic signal.',
            'This operation is called convolution, widely used in many academic fields such as image processing, acoustics, and electronics.',
            'The formula of convolution can be defined as follows:',
            'where <i>h(t)</i> is an impulse response and <i>x(t)</i> is an input signal.',
            'Applying this formula directly in this app to create auralised sounds is possible.',
            'However, this equation takes a long time to calculate - the server may crash due to the amount of calculation if the long sound file is input.',
            'Therefore, this app embeds the auralisation function with the modified version of convolution, which uses the Fourier transform.',
            'The convolution in the time domain is the same as the multiplication in the frequency domain.',
            'The following conversion shows the relationship between the Fourier transform and the convolution.',
            'Thus, the auralisation can also be achieved by the following steps:',
            'This is what the system of this app does in the auralisation section.',
            'The FFT-modified convolution method calculates way faster than the standard convolution; it reduces the computation complexity from <i>O(n<sup>2</sup>)</i> to <i>O(n</i> log<i>(n))</i>[1].'
        ],
        formulas: [
            '$$ { \\begin{eqnarray} y(t) &=& \\int_{-\\infty}^{\\infty}h(t-\\tau)x(\\tau)d\\tau \\\\ &=& h(t) * x(t)\\end{eqnarray} } $$',
            '$$ { \\begin{eqnarray} F(y(t)) &=& F(h(t) * x(t)) \\\\  &=& \\int_{-\\infty}^{\\infty}(\\int_{-\\infty}^{\\infty}h(t-\\tau)x(\\tau)d\\tau)e^{-j\\omega t}dt \\\\ &=&  \\int_{-\\infty}^{\\infty}x(\\tau) (\\int_{-\\infty}^{\\infty}h(t-\\tau)e^{-j\\omega t}dt) d\\tau \\\\ &=&  \\int_{-\\infty}^{\\infty}x(\\tau) (\\int_{-\\infty}^{\\infty}h(t-\\tau)e^{-j\\omega (t-\\tau)} dt) e^{-j\\omega \\tau}d\\tau \\\\ &=&  \\int_{-\\infty}^{\\infty}x(\\tau) e^{-j\\omega \\tau}d\\tau \\  F(h(t)) \\\\ &=& F(x(t)) \\  F(h(t)) \\end{eqnarray} } $$'
        ],
        images: [
            { src: require('../../../assets/theory/convolution.gif'),    caption: 'The sample gif of the convolution image.' },
        ],
        audios: [
            { src: require('@/assets/theory/singing.wav'),          title: 'Anechoic Operatic Voice' },
            { src: require('@/assets/theory/usina_main_s1_p1.wav'), title: 'The impulse response of Usina del Arte concert hall, Spain' },
            { src: require('@/assets/theory/convoluted.wav'),       title: 'Auralised Operatic Voice' },
        ],
    }
}
