version: "3"

services:

  rev-proxy:
    container_name: ${COMPOSE_PROJECT_NAME}_rev-proxy
    build:
      context: ./rev-proxy
    volumes:
      - ./static:/static
      - ./frontend:/var/www/html
    tty: true
    networks:
      default:
        ipv4_address: ${REV_PROXY_ADDRESS}

  redis:
    restart: always
    image: redis:6-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    volumes:
     - ./redis/data:/data
    ports:
      - "6379:6379"
    networks:
      default:
        ipv4_address: ${REDIS_ADDRESS}

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
