version: "3"

services:

  rev-proxy:
    build:
      dockerfile: Dockerfile
    ports:
      - "$DEV_PORT:$DEV_PORT"
    environment:
      - DEV_PORT=$DEV_PORT
      - DEV_DOMAIN_NAME=$DEV_DOMAIN_NAME
      - FRONTEND_DEV_ADDRESS=$FRONTEND_DEV_ADDRESS
      - BACKEND_DEV_ADDRESS=$BACKEND_DEV_ADDRESS

  frontend-dev:
    container_name: ${COMPOSE_PROJECT_NAME}_frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
      args:
        - HOME=$FRONTEND_HOME
    volumes:
      - ./frontend:$FRONTEND_HOME
      - $FRONTEND_HOME/node_modules/
    stdin_open: true
    tty: true
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME
      - DEV_DOMAIN_NAME=$DEV_DOMAIN_NAME
    networks:
      default:
        ipv4_address: $FRONTEND_DEV_ADDRESS

  backend-dev:
    container_name: ${COMPOSE_PROJECT_NAME}_backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
      args:
        - HOME=$BACKEND_HOME
    volumes:
      - ./backend:$BACKEND_HOME
      - $BACKEND_HOME/.pid
      - $BACKEND_HOME/config
    stdin_open: true
    tty: true
    environment:
      - HOME=$BACKEND_HOME
      - REDIS_ADDRESS=$REDIS_DEV_ADDRESS
    networks:
      default:
        ipv4_address: $BACKEND_DEV_ADDRESS
