version: "3"

services:

  rev-proxy:
    container_name: ${COMPOSE_PROJECT_NAME}_rev-proxy
    build:
      context: ../rev-proxy
    volumes:
      - ../static:/static
      - ../frontend/dist:/var/www/html
    tty: true
    networks:
      default:
        ipv4_address: $REV_PROXY_ADDRESS
    environment:
      - ENABLE_SSL=$ENABLE_SSL
      - EMAIL=$EMAIL

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: $NETWORK_SUBNET
