version: "3"

services:

  rev-proxy:
    container_name: ${COMPOSE_PROJECT_NAME}_rev-proxy
    build:
      context: ../rev-proxy
    ports:
      - "$HTTP_PORT:$HTTP_PORT"
      - "443:443"
    volumes:
      - ../static:/static
      - ../frontend/dist:/var/www/html
    tty: true
    networks:
      default:
        ipv4_address: $REV_PROXY_ADDRESS
    environment:
      - ENABLE_SSL=$ENABLE_SSL
      - DEV_ENABLE_SSL=$DEV_ENABLE_SSL
      - HTTP_PORT=$HTTP_PORT
      - EMAIL=$EMAIL

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: $NETWORK_SUBNET
