version: "3"

services:

  rev-proxy:
    build:
      dockerfile: Dockerfile-prodonly
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME
      - BACKEND_ADDRESS=$BACKEND_ADDRESS

  frontend:
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
    build:
      context: ../frontend
      args:
        - HOME=$FRONTEND_HOME
    volumes:
      - ../frontend:$FRONTEND_HOME
      - $FRONTEND_HOME/node_modules/
    stdin_open: true
    tty: true
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME
      - DEV_DOMAIN_NAME=$DEV_DOMAIN_NAME
    networks:
      default:
        ipv4_address: $FRONTEND_ADDRESS

  backend:
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    build:
      context: ../backend
      args:
        - HOME=$BACKEND_HOME
    volumes:
      - ../backend:$BACKEND_HOME
      - $BACKEND_HOME/.pid
      - $BACKEND_HOME/config
    stdin_open: true
    tty: true
    environment:
      - HOME=$BACKEND_HOME
      - REDIS_ADDRESS=$REDIS_ADDRESS
    networks:
      default:
        ipv4_address: $BACKEND_ADDRESS
