export const library = [
    
    {
        name:'1st Baptist Church Nashville',
        abbr:'1stBaptist',
        description: '1st Baptist Church East Nashville is a historic church at 601 Main Street in Nashville, Tennessee.',
        image:require('@/assets/img/1stBaptist.jpg'),
        plan:require('@/assets/plan/1stBaptist.png'),
        ir:[
            require('@/assets/ir/1stBaptist/stereo/1st_baptist_nashville_balcony.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '5.68',
                '62': '4.41',
                '125': '3.86',
                '250': '2.86',
                '500': '2.59',
                '1k': '2.61',
                '2k': '2.47',
                '4k': '2.02',
                '8k': '1.32',
                '16k': '0.92'
            },
            {
                'param': 'EDT (s)',
                '31': '7.95',
                '62': '3.22',
                '125': '3.09',
                '250': '2.58',
                '500': '2.06',
                '1k': '1.81',
                '2k': '1.68',
                '4k': '1.42',
                '8k': '0.91',
                '16k': '0.02'
            },
            {
                'param': 'D50',
                '31': '0.13',
                '62': '0.12',
                '125': '0.06',
                '250': '0.38',
                '500': '0.44',
                '1k': '0.54',
                '2k': '0.64',
                '4k': '0.63',
                '8k': '0.78',
                '16k': '0.99'
            },
            {
                'param': 'C50 (dB)',
                '31': '-8.36',
                '62': '-8.46',
                '125': '-11.69',
                '250': '-.2.17',
                '500': '-1.12',
                '1k': '0.76',
                '2k': '2.55',
                '4k': '2.34',
                '8k': '5.54',
                '16k': '19.26'
            },
            {
                'param': 'C80 (dB)',
                '31': '-7.48',
                '62': '-6.47',
                '125': '-9.22',
                '250': '0.00',
                '500': '1.34',
                '1k': '2.53',
                '2k': '3.76',
                '4k': '4.22',
                '8k': '7.06',
                '16k': '20.92'
            },
        ],
    },
    {
        name:'Alcuin College, University of York',
        abbr:'AlcuinCollege',
        description: 'Impulse responses recorded in a semi enclosed courtyard in Alcuin College on the University of York campus. The courtyard is formed of six buildings, with a 2.4m high wall connecting the buildings. Receivers S1R1, S1R2, and S1R3 sit at different distances forming an axis from source position S1. This axis was chosen as it is roughly parallel to the faces of the buildings to the north and south of the courtyard. Receivers S2R1, S2R2, and S2R3 form an axis from source S2 in order to approximate the diagonal span of the courtyard (limited by line of sight due to minor obstacles in the courtyard). These sets of receiver positions were chosen to compare the acoustic properties of a direct sound path orthogonal to the surrounding geometry with those of sound path at an oblique angle. S3R1 is positioned out of the line of sight of source S3, with acoustic coupling provided by the glass frontage of the north eastern building. Position S4 was inside a ground floor room adjacent to position S3. For positions S1R1 – S3R1 three impulse responses have been made; one with a single directional sound source (indicated by ‘front’ in the filename), one using a starter pistol (indicated by ‘spist’, and the other with an array of four directional sound sources pointing in different directions in an attempt to better approximate an omni-directional source. For positions S4R1-S4R2 only a single speakerorientation has been used due to the loudspeaker being inside a room. In each case the soundfield microphone is pointed directly at the loudspeaker.',
        image:require('@/assets/img/AlcuinCollege.jpg'),
        plan:require('@/assets/plan/AlcuinCollege.jpg'),
        ir:[
            require('@/assets/ir/AlcuinCollege/b-format/s1r1_spist_bform.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '1.99',
                '62': '2.22',
                '125': '1.99',
                '250': '1.49',
                '500': '1.61',
                '1k': '1.83',
                '2k': '1.77',
                '4k': '1.52',
                '8k': '1.20',
                '16k': '0.90'
            },
            {
                'param': 'EDT (s)',
                '31': '2.15',
                '62': '2.15',
                '125': '1.51',
                '250': '1.89',
                '500': '1.89',
                '1k': '1.89',
                '2k': '1.89',
                '4k': '1.51',
                '8k': '1.51',
                '16k': '0.23'
            },
            {
                'param': 'D50',
                '31': '0.14',
                '62': '0.41',
                '125': '0.46',
                '250': '0.32',
                '500': '0.47',
                '1k': '0.61',
                '2k': '0.34',
                '4k': '0.61',
                '8k': '0.65',
                '16k': '0.92'
            },
            {
                'param': 'C50 (dB)',
                '31': '-7.93',
                '62': '-1.58',
                '125': '-0.74',
                '250': '-3.35',
                '500': '-0.45',
                '1k': '1.96',
                '2k': '-2.84',
                '4k': '1.98',
                '8k': '2.61',
                '16k': '10.53'
            },
            {
                'param': 'C80 (dB)',
                '31': '-4.86',
                '62': '-0.13',
                '125': '1.04',
                '250': '-1.86',
                '500': '0.44',
                '1k': '2.48',
                '2k': '-1.58',
                '4k': '3.67',
                '8k': '3.74',
                '16k': '11.5'
            },
        ],
    },
    {
        name:'Arthur Sykes Rymer Auditorium, University of York',
        abbr:'ArthurSykes',
        description: '',
        image:require('@/assets/img/ArthurSykes.jpg'),
        ir:[
            require('@/assets/ir/ArthurSykes/b-format/s1r2.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '2.66',
                '62': '1.22',
                '125': '0.50',
                '250': '0.40',
                '500': '0.39',
                '1k': '0.38',
                '2k': '0.35',
                '4k': '0.31',
                '8k': '0.29',
                '16k': '0.18'
            },
            {
                'param': 'EDT (s)',
                '31': '0.76',
                '62': '0.51',
                '125': '0.51',
                '250': '0.38',
                '500': '0.51',
                '1k': '0.38',
                '2k': '0.38',
                '4k': '0.38',
                '8k': '0.25',
                '16k': '0.12'
            },
            {
                'param': 'D50',
                '31': '0.48',
                '62': '0.72',
                '125': '0.62',
                '250': '0.87',
                '500': '0.74',
                '1k': '0.86',
                '2k': '0.90',
                '4k': '0.91',
                '8k': '0.95',
                '16k': '1.00'
            },
            {
                'param': 'C50 (dB)',
                '31': '-0.34',
                '62': '4.02',
                '125': '2.18',
                '250': '8.10',
                '500': '4.55',
                '1k': '7.96',
                '2k': '9.68',
                '4k': '10.21',
                '8k': '12.47',
                '16k': '25.97'
            },
            {
                'param': 'C80 (dB)',
                '31': '4.62',
                '62': '11.53',
                '125': '9,76',
                '250': '14.65',
                '500': '10.60',
                '1k': '13.67',
                '2k': '16.40',
                '4k': '16.96',
                '8k': '20.20',
                '16k': '33.94'
            },
        ],
    },
    {
        name:'Central Hall, University of York',
        abbr:'CentralHall',
        description: 'These Impulse Responses were recorded in the Central Hall venue of the University of York. The space is primarily used for lectures and conferences; to emulate this scenario; a sound source was placed centered on the stage of the venue while six different microphone positions were chosen to sample the acoustics of the space. As can be seen in the images, the microphone placements were chosen by dividing Central Hall into four audience areas: the stalls on the floor in the centre of the space (Stalls), the central block of seating (positions 3C, 3L), the block to the left of the stage (positions 3C, 3L), and a single position just above the entrance to the Hall and below stairs (diagonal block of seating (2L)). Position 2L was chosen at a non-chair position, because of potential interesting filtering effects of the stairs above the receiver as well as due to the lack of chairs below it. The rear of the stage had a projection screen lowered that was 1.4 m from the source, as would have been the case during the simulated scenario. The microphone in the central region (Stalls) was placed in front of the speaker, 5.1 m from the source. All microphone positions were 1.2 m above the floor at seat positions while the source was positioned at 1.5 m above stage level (both in compliance with ISO 3382-1:2009). The soundfield microphone orientation was always chosen to be orthogonal to the line of seats, facing the centre of the space.',
        image:require('@/assets/img/CentralHall.jpg'),
        ir:[
            require('@/assets/ir/CentralHall/b-format/ir_centre_stalls.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '2.67',
                '62': '1.58',
                '125': '1.42',
                '250': '1.07',
                '500': '1.11',
                '1k': '1.12',
                '2k': '1.03',
                '4k': '0.86',
                '8k': '0.63',
                '16k': '1.95'
            },
            {
                'param': 'EDT (s)',
                '31': '1.54',
                '62': '1.54',
                '125': '1.67',
                '250': '1.41',
                '500': '1.28',
                '1k': '1.41',
                '2k': '1.41',
                '4k': '1.16',
                '8k': '1.03',
                '16k': '0.64'
            },
            {
                'param': 'D50',
                '31': '0.11',
                '62': '0.32',
                '125': '0.30',
                '250': '0.44',
                '500': '0.33',
                '1k': '0.19',
                '2k': '0.20',
                '4k': '0.24',
                '8k': '0.44',
                '16k': '0.72'
            },
            {
                'param': 'C50 (dB)',
                '31': '-9.17',
                '62': '-3.18',
                '125': '-3.67',
                '250': '-0.97',
                '500': '-3.14',
                '1k': '-6.30',
                '2k': '-6.13',
                '4k': '-4.95',
                '8k': '-1.04',
                '16k': '4.01'
            },
            {
                'param': 'C80 (dB)',
                '31': '-5.68',
                '62': '0.69',
                '125': '-1.77',
                '250': '0.35',
                '500': '-1.15',
                '1k': '-2.39',
                '2k': '-2.88',
                '4k': '-2.37',
                '8k': '1.27',
                '16k': '7.54'
            },
        ],
    },
    {
        name:'Creswell Crags',
        abbr:'CreswellCrags',
        description: 'A series of IRs recorded at Creswell Crags – including some recorded inside one of the caves using a sine sweep, and in the main gorge using a starter pistol.',
        image:require('@/assets/img/CreswellCrags.jpg'),
        ir:[
            require('@/assets/ir/CreswellCrags/b-format/2_s_mainlevel_r_mouth.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '1,35',
                '62': '1.19',
                '125': '1.12',
                '250': '0.88',
                '500': '0.73',
                '1k': '0.56',
                '2k': '0.46',
                '4k': '0.39',
                '8k': '0.31',
                '16k': '0.23'
            },
            {
                'param': 'EDT (s)',
                '31': '1.02',
                '62': '1.02',
                '125': '1.02',
                '250': '0.64',
                '500': '0.51',
                '1k': '0.38',
                '2k': '0.38',
                '4k': '0.25',
                '8k': '0.25',
                '16k': '0.12'
            },
            {
                'param': 'D50',
                '31': '0.53',
                '62': '0.53',
                '125': '0.64',
                '250': '0.69',
                '500': '0.85',
                '1k': '0.89',
                '2k': '0.92',
                '4k': '0.95',
                '8k': '0.97',
                '16k': '0.99'
            },
            {
                'param': 'C50 (dB)',
                '31': '0.45',
                '62': '0.52',
                '125': '2.44',
                '250': '3.48',
                '500': '7.65',
                '1k': '9.03',
                '2k': '10.51',
                '4k': '12.76',
                '8k': '14.76',
                '16k': '21.36'
            },
            {
                'param': 'C80 (dB)',
                '31': '5.58',
                '62': '4.13',
                '125': '4.30',
                '250': '8.72',
                '500': '9.72',
                '1k': '12.48',
                '2k': '14.90',
                '4k': '17.51',
                '8k': '20.55',
                '16k': '28.94'
            },
        ],
    },
    {
        name:'Elveden Hall (Suffolk England)',
        abbr:'ElvedenHall',
        description: 'Various rooms of Elveden Hall, captured in 2001 on Sony D10 DAT using pair of AKG 451s in XY, and starter’s pistol. The Hall, formerly the private residence of the Maharajah Duleep Singh and then the first Lord Iveagh, had at the time of these recordings not been lived in for decades. Elveden Hall, which was enlarged to its present size by Lord Iveagh at the end of the 19th century, consists of three floors in two enormous wings flanking a dramatic Marble Hall (which has featured as a location in films such as Eyes Wide Shut and Tomb Raider). The IRs offered here are a small subset of dozens made throughout the entire building, attempting to document every accessible room and closet, as part of research in a collaboration between artists Matt Rogalsky and Chlöe Steele entitled PERFECT IMPERFECT.',
        image:require('@/assets/img/ElvedenHall.jpg'),
        ir:[
            require('../../assets/ir/ElvedenHall/stereo/1a_marble_hall.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '40.51',
                '62': '22.68',
                '125': '8.1',
                '250': '3.58',
                '500': '4.26',
                '1k': '4.11',
                '2k': '3.91',
                '4k': '2.99',
                '8k': '1.74',
                '16k': '1.16'
            },
            {
                'param': 'EDT (s)',
                '31': '0.38',
                '62': '0.38',
                '125': '2.3',
                '250': '3.45',
                '500': '4.22',
                '1k': '4.22',
                '2k': '3.84',
                '4k': '2.81',
                '8k': '1.53',
                '16k': '0.89'
            },
            {
                'param': 'D50',
                '31': '0.88',
                '62': '0.89',
                '125': '0.32',
                '250': '0.10',
                '500': '0.14',
                '1k': '0.10',
                '2k': '0.12',
                '4k': '0.22',
                '8k': '0.35',
                '16k': '0.55'
            },
            {
                'param': 'C50 (dB)',
                '31': '8.5',
                '62': '9.2',
                '125': '-3.23',
                '250': '-9.43',
                '500': '-7.97',
                '1k': '-9.57',
                '2k': '-8.77',
                '4k': '-5.51',
                '8k': '-2.59',
                '16k': '0.93'
            },
            {
                'param': 'C80 (dB)',
                '31': '12.24',
                '62': '10.07',
                '125': '-1.05',
                '250': '-5.98',
                '500': '-5.26',
                '1k': '-6.71',
                '2k': '-5.68',
                '4k': '-2.94',
                '8k': '0.33',
                '16k': '4.21'
            },
        ],
    },
    {
        name:'Falkland Palace Bottle Dungeon',
        abbr:'FalklandPalaceDungeon',
        description: 'An Impulse Response recorded in the bottle dungeon found in Falkland Palace.',
        image:require('@/assets/img/FalklandPalaceDungeon.jpg'),
        ir:[
            require('../../assets/ir/FalklandPalaceDungeon/b-format/bottledungeon1_sf_edited.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '2.63',
                '62': '2.55',
                '125': '2.09',
                '250': '2.16',
                '500': '1.60',
                '1k': '1.11',
                '2k': '0.77',
                '4k': '0.63',
                '8k': '0.41',
                '16k': '0.30'
            },
            {
                'param': 'EDT (s)',
                '31': '0.65',
                '62': '2.57',
                '125': '1.42',
                '250': '1.81',
                '500': '1.17',
                '1k': '1.04',
                '2k': '0.78',
                '4k': '0.65',
                '8k': '0.40',
                '16k': '0.27'
            },
            {
                'param': 'D50',
                '31': '0.36',
                '62': '0.23',
                '125': '0.44',
                '250': '0.39',
                '500': '0.56',
                '1k': '0.57',
                '2k': '0.69',
                '4k': '0.71',
                '8k': '0.86',
                '16k': '0.94'
            },
            {
                'param': 'C50 (dB)',
                '31': '-2.43',
                '62': '-5.13',
                '125': '-1.09',
                '250': '-2.03',
                '500': '0.96',
                '1k': '1.23',
                '2k': '3.49',
                '4k': '3.81',
                '8k': '7.81',
                '16k': '12.01'
            },
            {
                'param': 'C80 (dB)',
                '31': '7.52',
                '62': '-3.36',
                '125': '1.45',
                '250': '0.89',
                '500': '3.09',
                '1k': '3.36',
                '2k': '6.14',
                '4k': '7.37',
                '8k': '12.4',
                '16k': '18.4'
            },
        ],
    },
    {
        name:'Falkland Palace Royal Tennis Court',
        abbr:'FalklandPalaceTennis',
        description: 'These impulse responses were recorded in a tennis court with no roof. The court is designed for Real Tennis, or Caitch and can be found at Falkland Palace in Fife. It was originally built for King James V of Scotland and construction began in 1539.',
        image:require('@/assets/img/FalklandPalaceTennis.jpg'),
        ir:[
            require('../../assets/ir/FalklandPalaceTennis/stereo/falkland_tennis_court_ortf.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '9.24',
                '62': '4.96',
                '125': '5.19',
                '250': '5.61',
                '500': '6.41',
                '1k': '5.48',
                '2k': '2.16',
                '4k': '1.09',
                '8k': '0.74',
                '16k': '0.52'
            },
            {
                'param': 'EDT (s)',
                '31': '1.90',
                '62': '1.90',
                '125': '1.51',
                '250': '1.26',
                '500': '1.39',
                '1k': '1.26',
                '2k': '1.00',
                '4k': '0.62',
                '8k': '0.49',
                '16k': '0.23'
            },
            {
                'param': 'D50',
                '31': '0.01',
                '62': '0.44',
                '125': '0.57',
                '250': '0.47',
                '500': '0.46',
                '1k': '0.70',
                '2k': '0.74',
                '4k': '0.71',
                '8k': '0.81',
                '16k': '0.92'
            },
            {
                'param': 'C50 (dB)',
                '31': '-22.00',
                '62': '-1.13',
                '125': '1.18',
                '250': '-0.54',
                '500': '-0.62',
                '1k': '3.62',
                '2k': '4.48',
                '4k': '3.96',
                '8k': '6.18',
                '16k': '10.69'
            },
            {
                'param': 'C80 (dB)',
                '31': '-18.71',
                '62': '-0.64',
                '125': '3.24',
                '250': '4.06',
                '500': '2.20',
                '1k': '4.68',
                '2k': '6.66',
                '4k': '9.47',
                '8k': '10.28',
                '16k': '14.57'
            },
        ],
    },
    {
        name:'Genesis 6 Studio - Live Room Drum Set Up',
        abbr:'Genesis6',
        description: 'Genesis 6 building is located within the York University Campus and is home to the Department of Electronic Engineering Audio Lab. Within this building is a large recording studio which consists of a control room and live recoding room which is used for teaching, researching and other academic practices. The live room is acoustically treated with 12 panels. Each panel consists of an MDF wooden frame and is filled with Rockwool acoustic insulation. Rockwool absorbs noise and reduces acoustic reflections by impeding sound transmission throughout the structure of the fibers, with the panels placed on the wall to absorb both upper and lower frequencies. Despite the low reverberation time caused by the acoustic treatment, the data collected was done so to recreate a 5 piece drum set setup within the space. In total there are 8 omi-directional Impulse Responses (IRs) each directly relating to a specific drum or cymbal, with their own individual location and height. Each drum piece source position was done so using a Swept Sine of 20Hz – 22kHz lasting 10 seconds, this was repeated four times in different directions. This process was used to capture the omnidirectional sound that the drum set would produce. The microphone receiver was positioned directly in front of the kick position and was set at ear level to simulate a listener being in the room.',
        image:require('@/assets/img/Genesis6.jpg'),
        ir:[
            require('../../assets/ir/Genesis6/b-format/hh_ir.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '0.80',
                '62': '0.57',
                '125': '0.28',
                '250': '0.27',
                '500': '0.21',
                '1k': '0.19',
                '2k': '0.21',
                '4k': '0.22',
                '8k': '0.21',
                '16k': '0.18'
            },
            {
                'param': 'EDT (s)',
                '31': '0.98',
                '62': '0.73',
                '125': '0.34',
                '250': '0.22',
                '500': '0.22',
                '1k': '0.22',
                '2k': '0.22',
                '4k': '0.22',
                '8k': '0.22',
                '16k': '0.22'
            },
            {
                'param': 'D50',
                '31': '0.26',
                '62': '0.46',
                '125': '0.92',
                '250': '0.94',
                '500': '0.98',
                '1k': '0.97',
                '2k': '0.97',
                '4k': '0.97',
                '8k': '0.96',
                '16k': '0.98'
            },
            {
                'param': 'C50 (dB)',
                '31': '-4.65',
                '62': '-0.74',
                '125': '10.63',
                '250': '11.92',
                '500': '16.19',
                '1k': '15.36',
                '2k': '14.75',
                '4k': '14.48',
                '8k': '13.44',
                '16k': '17.54'
            },
            {
                'param': 'C80 (dB)',
                '31': '-2.33',
                '62': '5.82',
                '125': '16.50',
                '250': '20.03',
                '500': '23.87',
                '1k': '26.00',
                '2k': '23.59',
                '4k': '22.54',
                '8k': '22.92',
                '16k': '27.99'
            },
        ],
    },
    {
        name:'Gill Heads Mine',
        abbr:'GillHeads',
        description: 'These Impulse Responses were recorded in a disused mine found near Trollers Gill called Gill Heads Mine. The mine was used to extract Lead and Fluorite and was closed down as recently as the 1980s. Impulse responses were recorded at two sites (labelled site 1 and site 2) inside the mine not more than 30 m from the entrance. For each site there are two sets of impulse responses: One is made with a single directional sound source (IR-1), and the other is made with an array of two directional sound sources pointing in opposite directions in an attempt to better approximate an omni-directional source (IR-2).',
        image:require('@/assets/img/GillHeads.jpg'),
        ir:[
            require('../../assets/ir/GillHeads/mono/mine_site1_1way_mono.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '2.29',
                '62': '2.01',
                '125': '1.33',
                '250': '1.12',
                '500': '0.88',
                '1k': '0.71',
                '2k': '0.64',
                '4k': '0.55',
                '8k': '0.47',
                '16k': '0.32'
            },
            {
                'param': 'EDT (s)',
                '31': '1.45',
                '62': '0.94',
                '125': '1.07',
                '250': '1.20',
                '500': '0.94',
                '1k': '0.68',
                '2k': '0.56',
                '4k': '0.43',
                '8k': '0.30',
                '16k': '0.17'
            },
            {
                'param': 'D50',
                '31': '0.43',
                '62': '0.71',
                '125': '0.75',
                '250': '0.44',
                '500': '0.46',
                '1k': '0.75',
                '2k': '0.81',
                '4k': '0.89',
                '8k': '0.93',
                '16k': '0.98'
            },
            {
                'param': 'C50 (dB)',
                '31': '-1.19',
                '62': '3.91',
                '125': '4.87',
                '250': '-1.12',
                '500': '-0.69',
                '1k': '4.82',
                '2k': '6.16',
                '4k': '8.99',
                '8k': '11.48',
                '16k': '17.18'
            },
            {
                'param': 'C80 (dB)',
                '31': '0.98',
                '62': '5.56',
                '125': '6.4',
                '250': '0.08',
                '500': '3.02',
                '1k': '7.26',
                '2k': '9.36',
                '4k': '12.86',
                '8k': '15.61',
                '16k': '22.62'
            },
        ],
    },
    {
        name:'Hamilton Mausoleum',
        abbr:'Hamilton',
        description: 'Construction on the Hamilton Mausoleum, Hamilton, Scotland, built for the 10th Duke of Hamilton, started in 1842 and was completed in 1858. It is constructed of marble and sandstone and is surmounted by a dome 36m in height, with two main spaces, a crypt in the lower section, and a chapel that was supposed to be used for worship. However the construction materials, size, shape and dimensions of the latter result in a complex, dense and very long reverberation, and hence render it almost useless for speech presentation. In fact the Guinness Book of World Records claims that the Hamilton Mausoleum has the longest “echo” of any building, recorded on 27 May 1994 as taking 15s for the sound of the reverberation caused by slamming one of the main doors to die away to nothing. The space is now often used by recording musicians for its unique acoustic properties. The interior of Hamilton Mausoleum is approximately octagonal in plan, with a diameter of 18 m. Each side of the octagon is either a plane wall or a further semicircular alcove. The results presented below having the microphone assembly in the centre and the source placed to one side, just outside one of the alcoves, giving a source-receiver distance of 4.8 m.',
        image:require('@/assets/img/Hamilton.jpg'),
        ir:[
            require('../../assets/ir/Hamilton/stereo/hm2_000_ortf_48k.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '29,05',
                '62': '22.88',
                '125': '19.27',
                '250': '15.06',
                '500': '12.45',
                '1k': '9.23',
                '2k': '6.02',
                '4k': '3.51',
                '8k': '1.50',
                '16k': '0.67'
            },
            {
                'param': 'EDT (s)',
                '31': '15.55',
                '62': '14.78',
                '125': '13.24',
                '250': '11.71',
                '500': '8.25',
                '1k': '6.20',
                '2k': '3.26',
                '4k': '0.70',
                '8k': '0.06',
                '16k': '0.06'
            },
            {
                'param': 'D50',
                '31': '0.05',
                '62': '0.17',
                '125': '0.13',
                '250': '0.33',
                '500': '0.40',
                '1k': '0.52',
                '2k': '0.63',
                '4k': '0.86',
                '8k': '0.95',
                '16k': '0.99'
            },
            {
                'param': 'C50 (dB)',
                '31': '-13.27',
                '62': '-6.86',
                '125': '-8.39',
                '250': '-3.02',
                '500': '-1.84',
                '1k': '0.26',
                '2k': '2.36',
                '4k': '8.00',
                '8k': '12.35',
                '16k': '19.69'
            },
            {
                'param': 'C80 (dB)',
                '31': '-5.36',
                '62': '-4.44',
                '125': '-7.08',
                '250': '-2.75',
                '500': '-1.45',
                '1k': '0.79',
                '2k': '3.20',
                '4k': '9.08',
                '8k': '13.27',
                '16k': '22.19'
            },
        ],
    },
    {
        name:'Heslington Church',
        abbr:'Heslington',
        description: 'Heslington Church (St. Paul’s) is a Methodist church situated on land where a church has been present since the 11th century. By the mid 19th century the building was considered too small and the material was in poor state. This led to the construction of what makes up the modern church on this site. When new housing estates and the university were built nearby, the church was once again considered too small and extensive extensions and alterations were made to the building in 1973. Of special note in these most recent alterations is the conversion of the chancel to a side-chapel, and the moving of the high altar to a large nave on the main space’s side wall. The end result was the complete reorientation of the church from the traditional lengthways layout to an unusual ‘landscape’ orientation, with the congregation facing the nave on the side wall. The reorientation of the space was a main reason we chose this location for our acoustic measurements. The unusual position of the priest’s speaking position relative to the congregation could give interesting results (especially for speech intelligibility) in a space originally acoustically designed for a more traditional church layout. The loudspeaker was set up in the nave just in front of the altar at standing head height. The first five receiver positions were situated in the middle of the front row of each set of pews at seated head height, allowing for measurements of speech intelligibility from typical listener positions in the new orientation of the church. A sixth receiver was positioned in the central rear section of the church, providing impulse responses intended for creative musical use. The seventh receiver position was in the corner of the room, in order to capture all of the modes of vibration present in the space.',
        image:require('@/assets/img/Heslington.jpg'),
        ir:[
            require('../../assets/ir/Heslington/b-format/impulseresponseheslingtonchurch-001.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '3.73',
                '62': '1.28',
                '125': '1.40',
                '250': '1.59',
                '500': '1.75',
                '1k': '1.65',
                '2k': '1.49',
                '4k': '1.14',
                '8k': '0.86',
                '16k': '0.59'
            },
            {
                'param': 'EDT (s)',
                '31': '1.38',
                '62': '1.25',
                '125': '1.12',
                '250': '1.76',
                '500': '1.89',
                '1k': '1.63',
                '2k': '1.63',
                '4k': '1.25',
                '8k': '0.99',
                '16k': '0.61'
            },
            {
                'param': 'D50',
                '31': '0.18',
                '62': '0.56',
                '125': '0.39',
                '250': '0.25',
                '500': '0.41',
                '1k': '0.45',
                '2k': '0.31',
                '4k': '0.43',
                '8k': '0.51',
                '16k': '0.78'
            },
            {
                'param': 'C50 (dB)',
                '31': '-6.51',
                '62': '1.09',
                '125': '-2.03',
                '250': '-4.70',
                '500': '-1.53',
                '1k': '-0.80',
                '2k': '-3.51',
                '4k': '-1.14',
                '8k': '0.11',
                '16k': '5.40'
            },
            {
                'param': 'C80 (dB)',
                '31': '-2.62',
                '62': '3.34',
                '125': '1.56',
                '250': '-2.20',
                '500': '1.51',
                '1k': '1.18',
                '2k': '-0.29',
                '4k': '1.59',
                '8k': '3.54',
                '16k': '9.34'
            },
        ],
    },
    {
        name:'Hoffmann Lime Kiln (Langcliffe, UK)',
        abbr:'Hoffmann',
        description: 'The Hoffmann Lime Kiln, situated in Langcliffe, UK within the Yorkshire Dales National Park is the most structurally complete of the remaining (Hoffmann) lime kilns in the UK. Built in 1873, the industrial scale lime kiln was commissioned by the Craven Lime Company and stood operational until 1931. For more historical and architectural information on the kiln visit the Craven Museum website: (https://www.cravenmuseum.org/archaeology/fact-sheets/the-hoffmann-kiln/). It’s large stone construction, semi-cylindrical shape and many open entrances provide an interesting basis for impulse response measurement. This page presents six Impulse Responses, taken from various positions within the kiln, each coming with their own spatial description and five auralised examples. All measurements were taken in accordance with the ISO-3382 regulations.',
        image:require('@/assets/img/Hoffmann.jpg'),
        ir:[
            require('../../assets/ir/Hoffmann/b-format/ir_p1.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '2.833',
                '62': '2.07',
                '125': '1.50',
                '250': '1.12',
                '500': '0.93',
                '1k': '0.71',
                '2k': '0.53',
                '4k': '0.38',
                '8k': '0.33',
                '16k': '0.26'
            },
            {
                'param': 'EDT (s)',
                '31': '0.92',
                '62': '0.79',
                '125': '0.66',
                '250': '0.66',
                '500': '0.66',
                '1k': '0.66',
                '2k': '0.40',
                '4k': '0.40',
                '8k': '0.40',
                '16k': '0.40'
            },
            {
                'param': 'D50',
                '31': '0.57',
                '62': '0.36',
                '125': '0.55',
                '250': '0.59',
                '500': '0.63',
                '1k': '0.67',
                '2k': '0.88',
                '4k': '0.90',
                '8k': '0.89',
                '16k': '0.92'
            },
            {
                'param': 'C50 (dB)',
                '31': '1.23',
                '62': '-2.56',
                '125': '0.86',
                '250': '1.65',
                '500': '2.27',
                '1k': '3.15',
                '2k': '8.69',
                '4k': '9.31',
                '8k': '9.07',
                '16k': '10.50'
            },
            {
                'param': 'C80 (dB)',
                '31': '4.92',
                '62': '6.35',
                '125': '6.90',
                '250': '7.01',
                '500': '5.57',
                '1k': '7.43',
                '2k': '12.71',
                '4k': '14.65',
                '8k': '14.91',
                '16k': '18.32'
            },
        ],
    },
    {
        name:'Innocent Railway Tunnel',
        abbr:'Innocent',
        description: 'The innocent railway tunnel, or St Leonards Tunnel, is found just South East of the centre of Edinburgh, close to Arthur’s Seat. It was built in 1831, and designed to accommodate two railway tracks. It is 517 m long and straight, with a semicircular cross-section that is 6 m wide and 4.5 m high. The tunnel was closed in 1968 when this section of the railway was dismantled. In 1981 it was reopened as a footpath and later a tarmac surface was applied the floor of the tunnel. It now is also used as a cycle path and is part of the national cycling network. The first measurement, labelled “middle”, was made roughly in the middle of the tunnel, with a distance of 10 m between the loudspeaker and the microphone. A second set of impulse responses was then measured at the South East entrance of the tunnel, at 6 different positions relative to entrance – labelled “entrance” (a), (b), (c), (d), (e) and (f). For the second set the distance between the loudspeaker and microphone was 5 m. The transducer positions for each measurement are illustrated by the diagrams found in the “Images” tab. For each measurement there are two sets of impulse responses: One is made with a single directional sound source (IR-1), and the other is made with an array of four directional sound sources pointing in different directions in an attempt to better approximate an omni-directional source (IR-2). The impulse responses recorded near the tunnel entrance have been normalised with respect to each other, so that the relative sound levels between measurements has been preserved.',
        image:require('@/assets/img/Innocent.jpg'),
        ir:[
            require('../../assets/ir/Innocent/mono/middle_tunnel_1way_mono.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '5.28',
                '62': '4.88',
                '125': '5.35',
                '250': '4.88',
                '500': '3.72',
                '1k': '2.82',
                '2k': '1.96',
                '4k': '1.31',
                '8k': '0.89',
                '16k': '0.48'
            },
            {
                'param': 'EDT (s)',
                '31': '0.94',
                '62': '4.26',
                '125': '3.62',
                '250': '2.86',
                '500': '1.58',
                '1k': '1.19',
                '2k': '0.68',
                '4k': '0.30',
                '8k': '0.30',
                '16k': '0.17'
            },
            {
                'param': 'D50',
                '31': '0.38',
                '62': '0.35',
                '125': '0.37',
                '250': '0.31',
                '500': '0.48',
                '1k': '0.57',
                '2k': '0.82',
                '4k': '0.94',
                '8k': '0.92',
                '16k': '0.98'
            },
            {
                'param': 'C50 (dB)',
                '31': '-2.10',
                '62': '-2.76',
                '125': '-2.22',
                '250': '-3.55',
                '500': '-0.30',
                '1k': '1.26',
                '2k': '6.66',
                '4k': '12.10',
                '8k': '10.40',
                '16k': '16.91'
            },
            {
                'param': 'C80 (dB)',
                '31': '5.18',
                '62': '-0.86',
                '125': '-0.87',
                '250': '1.01',
                '500': '3.16',
                '1k': '4.30',
                '2k': '8.42',
                '4k': '14.39',
                '8k': '13.95',
                '16k': '21.14'
            },
        ],
    },
    {
        name:'Jack Lyons Concert Hall',
        abbr:'JackLyons',
        description: '4 B-Format Room Impulse Responses recorded in the Jack Lyons Concert Hall at the University of York. The concert hall is hexagonally shaped with a seating capacity of up to 350 people. It regularly used for musical performance hosting a variety of performances from students and professionals alike. Each impulse has been measured at a different position in the room (conductor & the middle of each seating block). Each impulse consists of 4 speaker directions (front,back,left,right) that have been combined and normalised to simulate an omnidirectional source from the source position.',
        image:require('@/assets/img/JackLyons.jpg'),
        ir:[
            require('../../assets/ir/JackLyons/b-format/rir_jack_lyons_lp1_96k.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '3.55',
                '62': '2.28',
                '125': '2.18',
                '250': '2.05',
                '500': '1.89',
                '1k': '1.86',
                '2k': '1.69',
                '4k': '1.28',
                '8k': '0.90',
                '16k': '5.53'
            },
            {
                'param': 'EDT (s)',
                '31': '2.72',
                '62': '1.95',
                '125': '1.70',
                '250': '2.21',
                '500': '2.08',
                '1k': '2.08',
                '2k': '1.82',
                '4k': '1.44',
                '8k': '1.06',
                '16k': '0.42'
            },
            {
                'param': 'D50',
                '31': '0.06',
                '62': '0.19',
                '125': '0.25',
                '250': '0.12',
                '500': '0.15',
                '1k': '0.19',
                '2k': '0.20',
                '4k': '0.33',
                '8k': '0.41',
                '16k': '0.83'
            },
            {
                'param': 'C50 (dB)',
                '31': '-12.08',
                '62': '-6.40',
                '125': '-4.76',
                '250': '-8.49',
                '500': '-7.57',
                '1k': '-6.27',
                '2k': '-6.11',
                '4k': '-3.16',
                '8k': '-1.62',
                '16k': '6.90'
            },
            {
                'param': 'C80 (dB)',
                '31': '-7.02',
                '62': '-2.45',
                '125': '-0.66',
                '250': '-3.54',
                '500': '-2.86',
                '1k': '-2.84',
                '2k': '-2.37',
                '4k': '0.46',
                '8k': '2.63',
                '16k': '11.94'
            },
        ],
    },
    {
        name:'Koli National Park Summer',
        abbr:'KoliSummer',
        description: 'Impulse Responses measured in the forest of Koli National Park in Finland during mid-summer. There was no snow on the ground at this time. Impulse responses were captured at four sites and were measured using a B-format Soundfield microphone. For each site there are two sets of impulse responses: One is made with a single directional sound source (IR-1), and the other is made with an array of four directional sound sources pointing in different directions in an attempt to better approximate an omni-directional source (IR-2).',
        image:require('@/assets/img/KoliSummer.jpg'),
        ir:[
            require('../../assets/ir/KoliSummer/mono/koli_summer_site1_1way_mono.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '0.50',
                '62': '0.46',
                '125': '0.23',
                '250': '0.24',
                '500': '2.10',
                '1k': '1.67',
                '2k': '0.95',
                '4k': '0.54',
                '8k': '0.37',
                '16k': '0.23'
            },
            {
                'param': 'EDT (s)',
                '31': '0.48',
                '62': '0.36',
                '125': '0.23',
                '250': '0.10',
                '500': '0.10',
                '1k': '0.10',
                '2k': '0.10',
                '4k': '0.10',
                '8k': '0.10',
                '16k': '0.10'
            },
            {
                'param': 'D50',
                '31': '0.67',
                '62': '0.90',
                '125': '0.99',
                '250': '1.00',
                '500': '0.99',
                '1k': '0.98',
                '2k': '0.98',
                '4k': '0.98',
                '8k': '0.99',
                '16k': '1.00'
            },
            {
                'param': 'C50 (dB)',
                '31': '3.07',
                '62': '9.49',
                '125': '19.63',
                '250': '27.02',
                '500': '21.97',
                '1k': '17.95',
                '2k': '16.65',
                '4k': '18.11',
                '8k': '19.38',
                '16k': '24.88'
            },
            {
                'param': 'C80 (dB)',
                '31': '16.69',
                '62': '24.10',
                '125': '25.99',
                '250': '31.11',
                '500': '24.10',
                '1k': '20.60',
                '2k': '19.73',
                '4k': '22.26',
                '8k': '24.14',
                '16k': '32.11'
            },
        ],
    },
    {
        name:'Koli National Park Winter',
        abbr:'KoliWinter',
        description: 'Impulse Responses measured in the forest of Koli National Park in Finland during winter. The ground was covered in snow between 50 cm and 70 cm. Impulse responses were captured at four sites and were measured using a B-format Soundfield microphone. For each site there are two sets of impulse responses: One is made with a single directional sound source (IR-1), and the other is made with an array of four directional sound sources pointing in different directions in an attempt to better approximate an omni-directional source (IR-2).',
        image:require('@/assets/img/KoliWinter.jpg'),
        ir:[
            require('../../assets/ir/KoliWinter/mono/koli_snow_site1_1way_mono.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '0.16',
                '62': '0.18',
                '125': '0.07',
                '250': '0.18',
                '500': '1.06',
                '1k': '1.50',
                '2k': '0.97',
                '4k': '0.44',
                '8k': '0.33',
                '16k': '0.22'
            },
            {
                'param': 'EDT (s)',
                '31': '0.47',
                '62': '0.35',
                '125': '0.23',
                '250': '0.09',
                '500': '0.09',
                '1k': '0.09',
                '2k': '0.09',
                '4k': '0.09',
                '8k': '0.09',
                '16k': '0.09'
            },
            {
                'param': 'D50',
                '31': '0.54',
                '62': '0.89',
                '125': '1.00',
                '250': '1.00',
                '500': '1.00',
                '1k': '0.98',
                '2k': '0.96',
                '4k': '0.99',
                '8k': '1.00',
                '16k': '1.00'
            },
            {
                'param': 'C50 (dB)',
                '31': '0.74',
                '62': '8.94',
                '125': '38.77',
                '250': '32.80',
                '500': '26.45',
                '1k': '16.16',
                '2k': '14.21',
                '4k': '21.75',
                '8k': '23.07',
                '16k': '28.41'
            },
            {
                'param': 'C80 (dB)',
                '31': '10.65',
                '62': '18.68',
                '125': '42.65',
                '250': '34.97',
                '500': '29.19',
                '1k': '19.56',
                '2k': '17.83',
                '4k': '26.09',
                '8k': '28.15',
                '16k': '35.46'
            },
        ],
    },
    {
        name:'Lady Chapel, St Albans Cathedral',
        abbr:'LadyChapel',
        description: 'This data consists of 2 sets of impulse responses measured in the Lady Chapel at St Albans Cathedral. Measurements were taken at two different source and receiver positions, A and B. The positions of the sources and receivers for the two configurations, A and B, can be are described in the attached diagram. Each set consists of a 4 channel B-format response, a 2-channel ORTF stereo response, a 2-channel binaural stereo response and a 5-channel discrete microphone response (5.0) based on the Williams MMA microphone technique. Construction of the cathedral was started by the Normans in 1077 and hundreds of years of construction have resulted in a mixture of different architectural styles. The Lady Chapel is an example of architecture from the Decorated Gothic Period and was completed in 1327.',
        image:require('@/assets/img/LadyChapel.jpg'),
        ir:[
            require('../../assets/ir/LadyChapel/stereo/stalbans_a_ortf.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '3.44',
                '62': '3.28',
                '125': '3.31',
                '250': '2.78',
                '500': '2.49',
                '1k': '2.34',
                '2k': '2.10',
                '4k': '1.71',
                '8k': '1.05',
                '16k': '0.62'
            },
            {
                'param': 'EDT (s)',
                '31': '2.14',
                '62': '2.52',
                '125': '2.40',
                '250': '1.76',
                '500': '1.50',
                '1k': '1.50',
                '2k': '1.24',
                '4k': '0.60',
                '8k': '0.35',
                '16k': '0.22'
            },
            {
                'param': 'D50',
                '31': '0.13',
                '62': '0.34',
                '125': '0.19',
                '250': '0.56',
                '500': '0.57',
                '1k': '0.63',
                '2k': '0.67',
                '4k': '0.85',
                '8k': '0.91',
                '16k': '0.96'
            },
            {
                'param': 'C50 (dB)',
                '31': '-8.39',
                '62': '-2.96',
                '125': '-6.22',
                '250': '0.99',
                '500': '1.30',
                '1k': '2.35',
                '2k': '2.98',
                '4k': '7.66',
                '8k': '10.08',
                '16k': '14.40'
            },
            {
                'param': 'C80 (dB)',
                '31': '-5.66',
                '62': '-2.13',
                '125': '-0.65',
                '250': '2.74',
                '500': '2.74',
                '1k': '3.79',
                '2k': '4.44',
                '4k': '9.22',
                '8k': '12.20',
                '16k': '17.47'
            },
        ],
    },
    {
        name:'Maes Howe',
        abbr:'MaesHowe',
        description: 'Maes-Howe, Orkney, is one of the finest chambered cairns in Europe, and is dated to 3000BC. Prior work in the acoustics of ancient sites explores how the resonances exhibited therein might have affected regular human ritual and interaction with the space. It has been hypothesized that as these resonances are within the lower male vocal range, they may have been used in ritual to accentuate aspects of the voice. Unlike many similar ancient structures that have been studied to date, Maes Howe lends itself to the presence of strong modal frequencies. It is almost cubic in shape, of dimension 4.6m, with walls made from large, flat slabs of stone, resulting in smooth reflecting surfaces rather than more commonly found irregular placement of smaller stones.',
        image:require('@/assets/img/MaesHowe.jpg'),
        ir:[
            require('../../assets/ir/MaesHowe/stereo/mh3_000_ortf_48k.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '0.78',
                '62': '0.84',
                '125': '0.76',
                '250': '0.64',
                '500': '0.58',
                '1k': '0.51',
                '2k': '0.47',
                '4k': '0.43',
                '8k': '0.35',
                '16k': '0.29'
            },
            {
                'param': 'EDT (s)',
                '31': '0.75',
                '62': '0.75',
                '125': '0.62',
                '250': '0.37',
                '500': '0.24',
                '1k': '0.24',
                '2k': '0.24',
                '4k': '0.11',
                '8k': '0.11',
                '16k': '0.11'
            },
            {
                'param': 'D50',
                '31': '0.16',
                '62': '0.62',
                '125': '0.77',
                '250': '0.89',
                '500': '0.93',
                '1k': '0.92',
                '2k': '0.96',
                '4k': '0.99',
                '8k': '0.99',
                '16k': '1.00'
            },
            {
                'param': 'C50 (dB)',
                '31': '-7.32',
                '62': '2.22',
                '125': '5.13',
                '250': '9.28',
                '500': '11.18',
                '1k': '10.78',
                '2k': '14.25',
                '4k': '18.56',
                '8k': '20.39',
                '16k': '24.81'
            },
            {
                'param': 'C80 (dB)',
                '31': '3.03',
                '62': '6.03',
                '125': '8.65',
                '250': '12.24',
                '500': '15.25',
                '1k': '15.48',
                '2k': '18.38',
                '4k': '22.84',
                '8k': '25.53',
                '16k': '31.01'
            },
        ],
    },
    {
        name:'Newgrange',
        abbr:'Newgrange',
        description: 'IR recorded using the ESS method at Newgrange, a neolithic passage tomb in County Meath Ireland.',
        image:require('@/assets/img/Newgrange.jpg'),
        ir:[
            require('../../assets/ir/Newgrange/b-format/newgrange_s1r1.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '20.36',
                '62': '6.09',
                '125': '0.37',
                '250': '0.27',
                '500': '0.25',
                '1k': '0.26',
                '2k': '0.28',
                '4k': '0.28',
                '8k': '0.23',
                '16k': '0.17'
            },
            {
                'param': 'EDT (s)',
                '31': '0.78',
                '62': '0.78',
                '125': '0.27',
                '250': '0.27',
                '500': '0.27',
                '1k': '0.14',
                '2k': '0.14',
                '4k': '0.14',
                '8k': '0.14',
                '16k': '0.14'
            },
            {
                'param': 'D50',
                '31': '0.39',
                '62': '0.27',
                '125': '0.94',
                '250': '0.97',
                '500': '0.98',
                '1k': '0.98',
                '2k': '0.97',
                '4k': '0.98',
                '8k': '0.99',
                '16k': '1.00'
            },
            {
                'param': 'C50 (dB)',
                '31': '-1.92',
                '62': '-4.25',
                '125': '12.02',
                '250': '15.28',
                '500': '16.61',
                '1k': '16.61',
                '2k': '15.79',
                '4k': '16.79',
                '8k': '22.12',
                '16k': '25.81'
            },
            {
                'param': 'C80 (dB)',
                '31': '4.34',
                '62': '2.65',
                '125': '15.01',
                '250': '24.43',
                '500': '23.18',
                '1k': '23.67',
                '2k': '22.94',
                '4k': '22.33',
                '8k': '29.07',
                '16k': '34.54'
            },
        ],
    },
    {
        name:'R1 Nuclear Reactor Hall',
        abbr:'R1Nuclear',
        description: 'Built in 1954, the R1 Nuclear Reactor has not been used since 1970. However, the reactor hall still remains. It is found 25 metres underneath the KTH Royal Institute of Technology, near to Stolkholm.',
        image:require('@/assets/img/R1Nuclear.jpg'),
        ir:[
            require('../../assets/ir/R1Nuclear/stereo/r1_ortf.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '6.98',
                '62': '5.45',
                '125': '4.49',
                '250': '5.15',
                '500': '5.43',
                '1k': '4.78',
                '2k': '3.60',
                '4k': '2.51',
                '8k': '1.45',
                '16k': '0.98'
            },
            {
                'param': 'EDT (s)',
                '31': '6.15',
                '62': '5.12',
                '125': '3.84',
                '250': '4.35',
                '500': '4.35',
                '1k': '4.10',
                '2k': '2.82',
                '4k': '1.92',
                '8k': '1.03',
                '16k': '0.51'
            },
            {
                'param': 'D50',
                '31': '0.02',
                '62': '0.11',
                '125': '0.13',
                '250': '0.17',
                '500': '0.22',
                '1k': '0.24',
                '2k': '0.40',
                '4k': '0.50',
                '8k': '0.59',
                '16k': '0.79'
            },
            {
                'param': 'C50 (dB)',
                '31': '-17.33',
                '62': '-9.15',
                '125': '-8.29',
                '250': '-6.82',
                '500': '-5.61',
                '1k': '-4.93',
                '2k': '-1.73',
                '4k': '-0.03',
                '8k': '1.53',
                '16k': '5.76'
            },
            {
                'param': 'C80 (dB)',
                '31': '-15.65',
                '62': '-7.04',
                '125': '-4.51',
                '250': '-1.40',
                '500': '-3.53',
                '1k': '-3.24',
                '2k': '-0.01',
                '4k': '2.06',
                '8k': '5.07',
                '16k': '11.22'
            },
        ],
    },
    {
        name:'Ron Cooke Hub, University of York',
        abbr:'RonCooke',
        description: 'This stereo impulse response was recorded in the Ron Cooke Hub on the East Campus of the University of York. The process for the recordings of these Impulse Responses involved using a logarithmic sine sweep from 20Hz – 20kHz that was a minute long. The audio was played through a GenelecS30D and recorded through a FireFace800. The sample rate used was 96000. An omnidirectional source was not available. TO simulate an omnidirectional source, sine sweeps were recorded at 0,90,180 and 270 Degrees for each source position. These were then deconvolved,combined and normalized with respect to the loudest response. Three source positions and ten receiver positions were recorded for the space. The overall dimensions of the space are approximately 47.6m x 36m x 12m with a large reception area (Refer to floor plan attached). The floor plan also details source and receiver positions. First (S1) and Second (S2) Source Positions considered the three Receiver Positions at ground level (R1,R2,R3) which the Third Source (S3) also considering the receiver position on the first floor balcony (R4). The impulse response source-receiver combinations provided are: (S1,R1);(S1,R2);(S1,R3);(S2,R1);(S2,R2);(S2,R3);(S3,R1);(S3,R2);(S3,R3);(S3,R4).',
        image:require('@/assets/img/RonCooke.jpg'),
        ir:[
            require('../../assets/ir/RonCooke/b-format/fsfr.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '2.25',
                '62': '1.44',
                '125': '1.53',
                '250': '1.53',
                '500': '1.53',
                '1k': '1.53',
                '2k': '1.54',
                '4k': '1.33',
                '8k': '0.95',
                '16k': '0.62'
            },
            {
                'param': 'EDT (s)',
                '31': '1.57',
                '62': '1.19',
                '125': '0.42',
                '250': '1.32',
                '500': '2.08',
                '1k': '1.70',
                '2k': '1.83',
                '4k': '1.44',
                '8k': '0.93',
                '16k': '0.42'
            },
            {
                'param': 'D50',
                '31': '0.23',
                '62': '0.53',
                '125': '0.73',
                '250': '0.68',
                '500': '0.32',
                '1k': '0.42',
                '2k': '0.35',
                '4k': '0.37',
                '8k': '0.51',
                '16k': '0.79'
            },
            {
                'param': 'C50 (dB)',
                '31': '-5.32',
                '62': '0.56',
                '125': '4.32',
                '250': '3.20',
                '500': '-3.37',
                '1k': '-1.35',
                '2k': '-2.61',
                '4k': '-2.37',
                '8k': '0.18',
                '16k': '5.76'
            },
            {
                'param': 'C80 (dB)',
                '31': '-0.50',
                '62': '2.65',
                '125': '11.29',
                '250': '5.22',
                '500': '-0.98',
                '1k': '0.23',
                '2k': '-0.84',
                '4k': '0.19',
                '8k': '4.14',
                '16k': '11.32'
            },
        ],
    },
    {
        name:'Saint Lawrence Church Molebeek-Wersbeek Belgium',
        abbr:'SaintLawrence',
        description: 'This impulse response was made with a 4 sec sinesweep playing in the middle of the altar of the church with 2 spaced (70cm) omni DPA 4060 microphones in front of the altar. The recording was done in 96kHz 24bit.',
        image:require('@/assets/img/SaintLawrence.jpg'),
        ir:[
            require('../../assets/ir/SaintLawrence/stereo/ir_church_saint-laurentius_molenbeek_bekkevoort_belgium.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '1.71',
                '62': '1.59',
                '125': '1.51',
                '250': '1.40',
                '500': '1.57',
                '1k': '1.60',
                '2k': '1.59',
                '4k': '1.25',
                '8k': '0.87',
                '16k': '0.54'
            },
            {
                'param': 'EDT (s)',
                '31': '1.53',
                '62': '1.66',
                '125': '1.28',
                '250': '0.89',
                '500': '1.02',
                '1k': '1.15',
                '2k': '1.15',
                '4k': '0.64',
                '8k': '0.25',
                '16k': '0.25'
            },
            {
                'param': 'D50',
                '31': '0.13',
                '62': '0.38',
                '125': '0.51',
                '250': '0.68',
                '500': '0.74',
                '1k': '0.66',
                '2k': '0.69',
                '4k': '0.85',
                '8k': '0.91',
                '16k': '0.95'
            },
            {
                'param': 'C50 (dB)',
                '31': '-8.43',
                '62': '-2.21',
                '125': '0.25',
                '250': '3.36',
                '500': '4.58',
                '1k': '2.85',
                '2k': '3.52',
                '4k': '7.52',
                '8k': '10.22',
                '16k': '12.96'
            },
            {
                'param': 'C80 (dB)',
                '31': '0.01',
                '62': '-0.52',
                '125': '2.63',
                '250': '4.55',
                '500': '5.74',
                '1k': '4.15',
                '2k': '5.06',
                '4k': '8.93',
                '8k': '12.65',
                '16k': '16.15'
            },
        ],
    },
    {
        name:"Spokane Woman's Club",
        abbr:'Spokane',
        description: 'The Spokane Woman’s Club hall is a highly reflective space with bare walls, a hardwood floor and a curved ceiling. The space is roughly 84’x42′ with an average ceiling height of about 16′. The sweep was recorded before an event and deconvolved with Voxengo’s Deconvolver. The IR turned out very well. It allowed for seamless transition between the room sound recorded during a number of events, and the IR reverb used during post-production.',
        image:require('@/assets/img/Spokane.jpg'),
        ir:[
            require('../../assets/ir/Spokane/stereo/spokane_womans_club_ir.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '2.44',
                '62': '1.87',
                '125': '1.88',
                '250': '2.14',
                '500': '2.52',
                '1k': '2.55',
                '2k': '2.16',
                '4k': '1.61',
                '8k': '0.88',
                '16k': '0.65'
            },
            {
                'param': 'EDT (s)',
                '31': '1.46',
                '62': '1.33',
                '125': '1.33',
                '250': '1.72',
                '500': '1.84',
                '1k': '1.84',
                '2k': '1.72',
                '4k': '1.46',
                '8k': '0.56',
                '16k': '0.44'
            },
            {
                'param': 'D50',
                '31': '0.37',
                '62': '0.14',
                '125': '0.30',
                '250': '0.49',
                '500': '0.56',
                '1k': '0.55',
                '2k': '0.38',
                '4k': '0.41',
                '8k': '0.82',
                '16k': '0.89'
            },
            {
                'param': 'C50 (dB)',
                '31': '-2.34',
                '62': '-7.75',
                '125': '-3.61',
                '250': '-0.15',
                '500': '1.05',
                '1k': '0.90',
                '2k': '-2.08',
                '4k': '-1.61',
                '8k': '6.72',
                '16k': '9.03'
            },
            {
                'param': 'C80 (dB)',
                '31': '0.01',
                '62': '0.28',
                '125': '3.72',
                '250': '3.04',
                '500': '2.28',
                '1k': '2.37',
                '2k': '0.02',
                '4k': '0.79',
                '8k': '9.17',
                '16k': '12.58'
            },
        ],
    },
    {
        name:'Sports Centre, University of York',
        abbr:'SportsCentre',
        description: 'These measurements were made in a large sports hall in the sports centre at York university. The reverberation tail is very long.',
        image:require('@/assets/img/SportsCentre.jpeg'),
        ir:[
            require('../../assets/ir/SportsCentre/stereo/sportscentre_ortf.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '21.10',
                '62': '12.11',
                '125': '6.21',
                '250': '7.06',
                '500': '6.81',
                '1k': '6.52',
                '2k': '4.86',
                '4k': '4.07',
                '8k': '2.22',
                '16k': '1.45'
            },
            {
                'param': 'EDT (s)',
                '31': '1.74',
                '62': '2.13',
                '125': '4.17',
                '250': '5.84',
                '500': '5.45',
                '1k': '5.20',
                '2k': '4.05',
                '4k': '2.64',
                '8k': '1.10',
                '16k': '0.21'
            },
            {
                'param': 'D50',
                '31': '0.28',
                '62': '0.36',
                '125': '0.37',
                '250': '0.15',
                '500': '0.31',
                '1k': '0.32',
                '2k': '0.42',
                '4k': '0.62',
                '8k': '0.77',
                '16k': '0.93'
            },
            {
                'param': 'C50 (dB)',
                '31': '-4.10',
                '62': '-2.51',
                '125': '-2.28',
                '250': '-7.58',
                '500': '-3.44',
                '1k': '-3.31',
                '2k': '-1.43',
                '4k': '2.05',
                '8k': '5.18',
                '16k': '10.99'
            },
            {
                'param': 'C80 (dB)',
                '31': '0.44',
                '62': '-1.02',
                '125': '-1.14',
                '250': '-6.53',
                '500': '-3.08',
                '1k': '-2.90',
                '2k': '-1.08',
                '4k': '2.30',
                '8k': '5.46',
                '16k': '11.24'
            },
        ],
    },
    {
        name:'Spring Lane Building, University of York',
        abbr:'SpringLane',
        description: 'Completed in 2016, the Spring Lane teaching building is located on the University of York’s West Campus. It has an interesting modern design with an irregular floor layout. Impulse responses were taken on the second floor of the building’s main atrium. The first sound source was placed in the seating area at the top of the central stairs and the second was placed in the seating area on the bridge opposite the top of the stairs. These locations were chosen since these areas are the most populated when the building is in use, thus producing the most noise. The top floor was chosen in order to investigate the spectral effects of the concave glass skylight. Another factor in choosing the site was the sound-dampening acoustic panels that were installed in the construction of the building. The source and receiver were placed in the following configurations: Speaker position 1 – top of the stairs: S1R1 – top of the stairs; S1R2 – study corner; S1R3 – outside classroom left; S1R4 – bridge; S1R5 – bottom of the stairs; Speaker position 2 – bridge: S2R1 – bridge; S2R2 – far corner; S2R3 – top of the stairs; S2R4 – bottom of the stairs; An additional recording was taken in the building’s west stairwell, which serves as a comparison to the acoustically-treated main atrium. More information can be found in the analysis and images sections.',
        image:require('@/assets/img/SpringLane.jpg'),
        ir:[
            require('../../assets/ir/SpringLane/stereo/sp1_mp1_ir_stereo_trimmed.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '4.46',
                '62': '1.53',
                '125': '1.65',
                '250': '1.59',
                '500': '1.38',
                '1k': '0.94',
                '2k': '0.93',
                '4k': '0.87',
                '8k': '0.67',
                '16k': '1.54'
            },
            {
                'param': 'EDT (s)',
                '31': '1.59',
                '62': '1.33',
                '125': '1.07',
                '250': '1.07',
                '500': '1.20',
                '1k': '1.07',
                '2k': '0.95',
                '4k': '0.82',
                '8k': '0.69',
                '16k': '0.43'
            },
            {
                'param': 'D50',
                '31': '0.20',
                '62': '0.30',
                '125': '0.39',
                '250': '0.56',
                '500': '0.43',
                '1k': '0.53',
                '2k': '0.52',
                '4k': '0.57',
                '8k': '0.68',
                '16k': '0.86'
            },
            {
                'param': 'C50 (dB)',
                '31': '-5.99',
                '62': '-3.59',
                '125': '-1.96',
                '250': '1.05',
                '500': '-1.16',
                '1k': '0.51',
                '2k': '0.41',
                '4k': '1.21',
                '8k': '3.23',
                '16k': '7.73'
            },
            {
                'param': 'C80 (dB)',
                '31': '0.74',
                '62': '0.26',
                '125': '3.76',
                '250': '3.18',
                '500': '1.94',
                '1k': '3.67',
                '2k': '4.06',
                '4k': '5.35',
                '8k': '7.25',
                '16k': '12.52'
            },
        ],
    },
    {
        name:"St Andrew's Church",
        abbr:'StAndrews',
        description: 'St Andrew’s Church, built in the 14th Century, has one of the finest examples of in-situ acoustic jars (vases or pots) in the UK. These jars were common to European church construction in the late Middle Ages and are said to be based on the ideas of Roman architect Vitruvius, who discussed the use of resonant jars in the design of amphitheatres to provide clarity of voice presentation. They are designed as Helmholtz resonators, giving narrow band energy absorption according to the natural frequency of the jar although there is little conclusive acoustical evidence to show that they behave as designed. Studies suggest that the success or otherwise of these devices depends on the number of jars used and their placement, as well as the characteristics of the building and jars themselves. In anechoic and reverberant chambers the absorption effects of such jars are weak and highly selective, although can be significant below 200Hz. Together with their additional diffusive effects, the jars potentially help to eliminate strong normal modes and hence can be made effective with careful tuning and positioning. St Andrew’s Church has 11 jars placed high in the chancel, 6 in the north wall and 5 in the south, arranged at irregular intervals such that there are no directly opposite pairs.',
        image:require('@/assets/img/StAndrews.jpg'),
        ir:[
            require('../../assets/ir/StAndrews/stereo/lyd3_000_ortf_48k.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '1.92',
                '62': '2.35',
                '125': '1.42',
                '250': '1.25',
                '500': '1.22',
                '1k': '1.45',
                '2k': '1.42',
                '4k': '1.22',
                '8k': '0.85',
                '16k': '0.55'
            },
            {
                'param': 'EDT (s)',
                '31': '1.57',
                '62': '1.31',
                '125': '1.05',
                '250': '1.05',
                '500': '0.93',
                '1k': '1.05',
                '2k': '0.80',
                '4k': '0.67',
                '8k': '0.29',
                '16k': '0.16'
            },
            {
                'param': 'D50',
                '31': '0.09',
                '62': '0.63',
                '125': '0.68',
                '250': '0.61',
                '500': '0.64',
                '1k': '0.73',
                '2k': '0.79',
                '4k': '0.85',
                '8k': '0.93',
                '16k': '0.98'
            },
            {
                'param': 'C50 (dB)',
                '31': '-10.25',
                '62': '2.22',
                '125': '3.27',
                '250': '1.94',
                '500': '2.42',
                '1k': '4.30',
                '2k': '5.69',
                '4k': '7.51',
                '8k': '11.29',
                '16k': '16.67'
            },
            {
                'param': 'C80 (dB)',
                '31': '-2.38',
                '62': '3.99',
                '125': '5.42',
                '250': '4.58',
                '500': '5.00',
                '1k': '5.90',
                '2k': '6.95',
                '4k': '8.97',
                '8k': '12.99',
                '16k': '19.58'
            },
        ],
    },
    {
        name:"St Matthew's Church - Walsall",
        abbr:'StMatthews',
        description: '',
        image:require('@/assets/img/StMatthews.jpg'),
        ir:[
            require('../../assets/ir/StMatthews/mono/ir_-_location_1_s1_-_r1.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '5.19',
                '62': '1.15',
                '125': '1.30',
                '250': '1.59',
                '500': '1.82',
                '1k': '1.86',
                '2k': '1.71',
                '4k': '1.40',
                '8k': '1.00',
                '16k': '0.75'
            },
            {
                'param': 'EDT (s)',
                '31': '1.19',
                '62': '1.19',
                '125': '0.94',
                '250': '1.58',
                '500': '1.58',
                '1k': '1.19',
                '2k': '1.32',
                '4k': '1.19',
                '8k': '0.81',
                '16k': '0.55'
            },
            {
                'param': 'D50',
                '31': '0.09',
                '62': '0.28',
                '125': '0.21',
                '250': '0.30',
                '500': '0.43',
                '1k': '0.65',
                '2k': '0.45',
                '4k': '0.51',
                '8k': '0.66',
                '16k': '0.86'
            },
            {
                'param': 'C50 (dB)',
                '31': '-10.19',
                '62': '-4.01',
                '125': '-5.85',
                '250': '-3.65',
                '500': '-1.23',
                '1k': '2.75',
                '2k': '-0.84',
                '4k': '0.19',
                '8k': '2.88',
                '16k': '7.81'
            },
            {
                'param': 'C80 (dB)',
                '31': '-3.63',
                '62': '1.35',
                '125': '2.57',
                '250': '-0.84',
                '500': '1.03',
                '1k': '3.95',
                '2k': '1.03',
                '4k': '2.67',
                '8k': '5.95',
                '16k': '11.14'
            },
        ],
    },
    {
        name:"St George's Episcopal Church",
        abbr:'StGeorges',
        description: '',
        image:require('@/assets/img/StGeorges.jpg'),
        ir:[
            require('../../assets/ir/StGeorges/stereo/st_georges_far.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '6.51',
                '62': '6.05',
                '125': '3.96',
                '250': '2.55',
                '500': '2.58',
                '1k': '2.94',
                '2k': '2.86',
                '4k': '2.50',
                '8k': '1.71',
                '16k': '1.10'
            },
            {
                'param': 'EDT (s)',
                '31': '9.36',
                '62': '2.06',
                '125': '2.06',
                '250': '2.45',
                '500': '2.70',
                '1k': '2.19',
                '2k': '2.06',
                '4k': '2.06',
                '8k': '0.91',
                '16k': '0.14'
            },
            {
                'param': 'D50',
                '31': '0.14',
                '62': '0.27',
                '125': '0.27',
                '250': '0.30',
                '500': '0.19',
                '1k': '0.51',
                '2k': '0.54',
                '4k': '0.44',
                '8k': '0.73',
                '16k': '0.98'
            },
            {
                'param': 'C50 (dB)',
                '31': '-7.98',
                '62': '-4.38',
                '125': '-4.22',
                '250': '-3.74',
                '500': '-6.38',
                '1k': '0.12',
                '2k': '0.67',
                '4k': '-1.10',
                '8k': '4.24',
                '16k': '16.25'
            },
            {
                'param': 'C80 (dB)',
                '31': '-4.99',
                '62': '-1.69',
                '125': '-1.70',
                '250': '-1.63',
                '500': '-4.04',
                '1k': '1.79',
                '2k': '3.04',
                '4k': '0.83',
                '8k': '5.99',
                '16k': '18.36'
            },
        ],
    },
    {
        name:"St Margaret's Church - National Centre for Early Music",
        abbr:'StMargarets',
        description: 'Impulse responses were captured in St. Margaret’s Church in York. The space has since been redeveloped and is now used for concerts and conferences, and for this reason its acoustics have been extensively redesigned by ARUP Acoustics. Using different configurations at the panel absorbers (reflective on the one side, absorbing on the other) as well as drapes in the roof the acoustic behaviour can be changed. The first cofiguration, for musical/opera performances, includes drapes and 75% of panels in use (open). For the second configuration, the drapes and 100% of the panels are in use, suitable for lectures/speech. For the third configuration, suitable for music recitals, only the drapes are in use (all panel absorbers closed). Photographs show the configurations being used. Receiver positions were chosen in order to create a virtual grid of 26 points equidistant from each other in the audience area. The source was placed as a performer would be in the space. The positions of these sources and receivers are described in the attached diagram. —–NOTE: The Impulse Responses have been updated on 22nd March 2012. ',
        image:require('@/assets/img/StMargarets.jpg'),
        ir:[
            require('../../assets/ir/StMargarets/b-format/r1_1st_configuration.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '21.00',
                '62': '2.69',
                '125': '1.82',
                '250': '1.60',
                '500': '1.49',
                '1k': '1.40',
                '2k': '1.30',
                '4k': '1.15',
                '8k': '0.81',
                '16k': '0.52'
            },
            {
                'param': 'EDT (s)',
                '31': '2.39',
                '62': '2.13',
                '125': '1.62',
                '250': '1.87',
                '500': '1.62',
                '1k': '1.49',
                '2k': '1.36',
                '4k': '1.11',
                '8k': '0.59',
                '16k': '0.47'
            },
            {
                'param': 'D50',
                '31': '0.06',
                '62': '0.22',
                '125': '0.41',
                '250': '0.22',
                '500': '0.37',
                '1k': '0.37',
                '2k': '0.43',
                '4k': '0.46',
                '8k': '0.71',
                '16k': '0.85'
            },
            {
                'param': 'C50 (dB)',
                '31': '-12.22',
                '62': '-5.48',
                '125': '-1.58',
                '250': '-5.38',
                '500': '-2.29',
                '1k': '-2.22',
                '2k': '-1.22',
                '4k': '-0.78',
                '8k': '3.80',
                '16k': '7.44'
            },
            {
                'param': 'C80 (dB)',
                '31': '-3.16',
                '62': '-3.53',
                '125': '-0.03',
                '250': '-1.41',
                '500': '-0.58',
                '1k': '0.53',
                '2k': '1.52',
                '4k': '3.20',
                '8k': '7.91',
                '16k': '12.48'
            },
        ],
    },
    {
        name:"St Mary's Abbey Reconstruction",
        abbr:'StMarys',
        description: 'The abbey of St. Mary was mostly destroyed during the dissolution under the rule of Henry VIII and now only ruins remain. These ruins can be found in the Museum Gardens adjacent to the river Ouse in York city. Virtual models of this now derelict church were built using measurements taken from scaled plans and other sources of architectural evidence. Impulse responses were then created using ray-based room acoustic modelling software. Three different models of the church were used with increasing levels of detail in their geometric structure, referred to as Phase 1, Phase 2 and Phase 3. The work was carried out as part of a Bachelor of Engineering project at the Audiolab in the University of York.',
        image:require('@/assets/img/StMarys.jpg'),
        ir:[
            require('../../assets/ir/StMarys/stereo/phase1_stereo.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '16.75',
                '62': '16.38',
                '125': '16.13',
                '250': '15.20',
                '500': '13.73',
                '1k': '12.29',
                '2k': '9.88',
                '4k': '7.49',
                '8k': '5.07',
                '16k': '5.51'
            },
            {
                'param': 'EDT (s)',
                '31': '21.30',
                '62': '20.66',
                '125': '18.49',
                '250': '17.72',
                '500': '15.93',
                '1k': '14.14',
                '2k': '9.91',
                '4k': '5.82',
                '8k': '2.62',
                '16k': '1.46'
            },
            {
                'param': 'D50',
                '31': '0.00',
                '62': '0.00',
                '125': '0.00',
                '250': '0.01',
                '500': '0.02',
                '1k': '0.05',
                '2k': '0.04',
                '4k': '0.14',
                '8k': '0.35',
                '16k': '0.55'
            },
            {
                'param': 'C50 (dB)',
                '31': '-25.44',
                '62': '-25.40',
                '125': '-25.77',
                '250': '-22.80',
                '500': '-17.47',
                '1k': '-12.83',
                '2k': '-13.53',
                '4k': '-8.01',
                '8k': '-2.76',
                '16k': '0.79'
            },
            {
                'param': 'C80 (dB)',
                '31': '-23.51',
                '62': '-22.95',
                '125': '-20.96',
                '250': '-20.57',
                '500': '-16.92',
                '1k': '-12.57',
                '2k': '-13.02',
                '4k': '-7.63',
                '8k': '-2.37',
                '16k': '1.26'
            },
        ],
    },
    {
        name:"St Patrik's Church, Patrigton",
        abbr:'StPatriks',
        description: 'St Patrick’s Church in Patrington dates back to the medieval era and expresses the decorated design of English Gothic Churches of the early 14th century. It has a cruciform plan, with an external length of about 46 meters, a breadth of 27 meters and a height of 57.5 meters up to the very top of the central tower. These impulse responses were measured in the real world. 3 sets of measurements were recorded for 3 different source-reciever configurations (S1-R1, S2-R2 and S3-R3). The positions of these sources and receivers are described in the attached diagram.',
        image:require('@/assets/img/StPatriks.jpg'),
        ir:[
            require('../../assets/ir/StPatricks/stereo/ortf_s1r1.wav'),
        ],
        acousticParams:[
            {
                'param': 'RT60 (s)',
                '31': '4.94',
                '62': '1.92',
                '125': '1.61',
                '250': '1.80',
                '500': '1.83',
                '1k': '1.86',
                '2k': '1.65',
                '4k': '1.39',
                '8k': '1.06',
                '16k': '0.74'
            },
            {
                'param': 'EDT (s)',
                '31': '2.25',
                '62': '1.74',
                '125': '1.49',
                '250': '1.74',
                '500': '2.13',
                '1k': '1.74',
                '2k': '1.36',
                '4k': '1.10',
                '8k': '0.59',
                '16k': '0.33'
            },
            {
                'param': 'D50',
                '31': '0.17',
                '62': '0.35',
                '125': '0.43',
                '250': '0.19',
                '500': '0.30',
                '1k': '0.43',
                '2k': '0.59',
                '4k': '0.69',
                '8k': '0.82',
                '16k': '0.92'
            },
            {
                'param': 'C50 (dB)',
                '31': '-7.01',
                '62': '-2.67',
                '125': '-1.29',
                '250': '-6.35',
                '500': '-3.73',
                '1k': '-1.31',
                '2k': '1.62',
                '4k': '3.56',
                '8k': '6.49',
                '16k': '10.33'
            },
            {
                'param': 'C80 (dB)',
                '31': '-0.74',
                '62': '-0.09',
                '125': '1.18',
                '250': '0.64',
                '500': '-1.13',
                '1k': '1.29',
                '2k': '3.23',
                '4k': '5.30',
                '8k': '8.71',
                '16k': '13.14'
            },
        ],
    },
    {
        name:"St Patrik's Church, Patrigton - Model",
        abbr:'StPatriksModel',
        description: '',
        image:require('@/assets/img/StPatriksModel.png'),
    },
    {
        name:"Stairway, University of York",
        abbr:'Stairway',
        description: '',
        image:require('@/assets/img/Stairway.jpg'),
    },
    {
        name:"Terry's Factory Warehouse",
        abbr:'TerrysFactory',
        description: '',
        image:require('@/assets/img/TerrysFactory.jpg'),
    },
    {
        name:"Terry's Typing Room",
        abbr:'TerrysTypingRoom',
        description: '',
        image:require('@/assets/img/TerrysTypingRoom.jpg'),
    },
    {
        name:"The Dixon Studio Theatre - University of York",
        abbr:'DixonStudio',
        description: '',
        image:require('@/assets/img/DixonStudio.jpg'),
    },
    {
        name:"The Shrine and Parish Church of All Saints North Street",
        abbr:'ShrineAndParish',
        description: '',
        image:require('@/assets/img/ShrineAndParish.jpg'),
    },
    {
        name:"Troller's Gill",
        abbr:'TrollersGill',
        description: '',
        image:require('@/assets/img/TrollersGill.jpg'),
    },
    {
        name:"Tvísöngur Sound Sculpture, Iceland (Model)",
        abbr:'Tvisongur',
        description: '',
        image:require('@/assets/img/Tvisongur.png'),
    },
    {
        name:"Tyndall Bruce Monument",
        abbr:'TyndallBruce',
        description: '',
        image:require('@/assets/img/TyndallBruce.jpg'),
    },
    {
        name:"Usina del Arte Symphony Hall",
        abbr:'UsinaDelArte',
        description: '',
        image:require('@/assets/img/UsinaDelArte.jpg'),
    },
    {
        name:"York Guildhall Council Chamber",
        abbr:'YorkGuildhall',
        description: '',
        image:require('@/assets/img/YorkGuildhall.jpg'),
    },
    {
        name:"York Minster",
        abbr:'YorkMinster',
        description: '',
        image:require('@/assets/img/YorkMinster.jpg'),
    },
]

